master:
  enabled: true
  replicas: 1
  affinity: ""
  data:
    type: "persistentVolumeClaim"
    size: "5Gi"
    storageClass: "custom-longhorn-slower-sc"

  logs:
    type: "persistentVolumeClaim"
    size: "5Gi"
    storageClass: "custom-longhorn-slower-sc"

volume:
  enabled: true
  replicas: 1
  affinity: ""

  dataDirs:
    - name: data1
      type: "persistentVolumeClaim"
      size: "300Gi"
      maxVolumes: 0 # If set to zero, the limit will be auto configured

filer:
  enabled: true
  replicas: 1
  storage: 5Gi
  storageClass: "custom-longhorn-slower-sc"

  data:
    type: "persistentVolumeClaim"
    size: "5Gi"
    storageClass: "custom-longhorn-slower-sc"

  logs:
    type: "persistentVolumeClaim"
    size: "5Gi"
    storageClass: "custom-longhorn-slower-sc"

  s3:
    enabled: true
    enableAuth: true
    existingConfigSecret: "sw-s3-auth-secret"

s3:
  enabled: true
  replicas: 1
  enableAuth: true
  existingConfigSecret: "sw-s3-auth-secret"

  logs:
    type: "persistentVolumeClaim"
    size: "5Gi"
    storageClass: "custom-longhorn-slower-sc"
