apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweed-filer-ingress
  namespace: seaweedfs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - secretName: vss-tls-cert
  rules:
    - host: swfs-filer.lab.s-miras.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-filer
                port:
                  number: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweed-s3-ingress
  namespace: seaweedfs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - secretName: vss-tls-cert
  rules:
    - host: swfs-s3.lab.s-miras.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-s3
                port:
                  number: 8333
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-s3-nodeport
  namespace: seaweedfs
spec:
  type: NodePort
  ports:
    - port: 8333
      targetPort: 8333
      nodePort: 30333
      protocol: TCP
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/instance: seaweedfs
    app.kubernetes.io/component: s3
