apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ducklake-catalog-db-route
  namespace: ducklake-catalog
spec:
  entryPoints:
    - postgres-ducklake-catalog
  routes:
    - match: HostSNI(`*`)
      services:
        - name: ducklake-catalog-cnpg-db-rw
          port: 5432
