postgresql:
  auth:
    database: kaneo
    username: kaneo_user
    existingSecret: "kaneo-secrets"
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  persistence:
    size: 15Gi
    storageClass: "custom-longhorn-slower-sc"
api:
  image:
    repository: ghcr.io/usekaneo/api
    tag: 2.1.6
    pullPolicy: IfNotPresent
  env:
    jwtAccess: "your-secure-jwt-secret"
  # env:
  #   existingSecret:
  #     enabled: true
  #     name: "kaneo-secrets"
  #     key: jwt-access
  #   disableRegistration: false
web:
  env:
    apiUrl: "https://kaneo.lab.s-miras.com"
ingress:
  enabled: false
