postgresql:
  auth:
    database: kaneo
    username: kaneo_user
    existingSecret: "kaneo-secrets"
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  persistence:
    size: 15Gi
    storageClass: "custom-longhorn-slower-sc"
api:
  image:
    repository: ghcr.io/usekaneo/api
    tag: 2.1.23
    pullPolicy: IfNotPresent
  env:
    existingSecret:
      enabled: true
      name: "kaneo-secrets"
      key: jwt-access
    disableRegistration: false
    betterAuthSecret:
      name: "kaneo-secrets"
      key: better-auth-secret
web:
  env:
    apiUrl: "https://kaneo.lab.s-miras.com"
ingress:
  enabled: false
