apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: airflow-cnpg-db
  namespace: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - airflow
  selector:
    matchLabels:
      cnpg.io/cluster: airflow-cnpg-db
  podMetricsEndpoints:
    - port: metrics
