apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: airflow-cnpg-db
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: airflow-cnpg-db
  podMetricsEndpoints:
    - port: metrics
