apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ducklake-catalog-cnpg-db
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: ducklake-catalog-cnpg-db
  namespaceSelector:
    matchNames:
      - ducklake-catalog
  podMetricsEndpoints:
    - port: metrics
