apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dwh-cnpg-db
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: dwh-cnpg-db
  namespaceSelector:
    matchNames:
      - dwh
  podMetricsEndpoints:
    - port: metrics
