apiVersion: v1
kind: Service
metadata:
  name: grafana-tailscale
  namespace: kube-prometheus-stack
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "grafana"
    tailscale.com/backend-protocol: "http"
    tailscale.com/funnel: "false"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 443
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kube-prometheus-stack
