apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: airflow-db-route
  namespace: airflow
spec:
  entryPoints:
    - postgres-airflow
  routes:
    - match: HostSNI(`*`)
      services:
        - name: airflow-cnpg-db-rw
          port: 5432
