apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: dwh-db-route
  namespace: dwh
spec:
  entryPoints:
    - postgres-dwh
  routes:
    - match: HostSNI(`*`)
      services:
        - name: dwh-cnpg-db-rw
          port: 5432
